import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "error",
    nursery: "error",
    pedantic: "error",
    perf: "error",
    restriction: "error",
    style: "error",
    suspicious: "error",
  },
  plugins: ["import"],
  rules: {
    "eslint/default-case": "off",
    "eslint/func-style": ["error", "declaration"],
    "eslint/id-length": ["error", { exceptions: ["_"] }],
    "eslint/max-lines-per-function": ["error", { skipBlankLines: true, skipComments: true }],
    "eslint/max-params": ["error", { max: 4 }],
    "eslint/max-statements": ["error", { max: 20 }],
    "eslint/no-continue": "off",
    "eslint/no-duplicate-imports": [
      "error",
      { allowSeparateTypeImports: true, includeExports: true },
    ],
    "eslint/no-ternary": "off",
    "eslint/no-use-before-define": "off",
    "import/exports-last": "off",
    "import/group-exports": "off",
    "import/max-dependencies": ["error", { ignoreTypeImports: true }],
    "import/no-default-export": "off",
    "import/no-named-export": "off",
    "import/prefer-default-export": "off",
    "oxc/no-async-await": "off",
    "oxc/no-optional-chaining": "off",
    "oxc/no-rest-spread-properties": "off",
    "typescript/ban-types": "off",
    "typescript/explicit-function-return-type": "off",
    "typescript/no-empty-object-type": ["error", { allowObjectTypes: "always" }],
    "typescript/no-non-null-assertion": "off",
    "typescript/parameter-properties": ["error", { prefer: "parameter-property" }],
    "unicorn/no-array-callback-reference": "off",
    "unicorn/no-null": "off",
    "unicorn/no-useless-undefined": ["error", { checkArguments: false }],
    "unicorn/prefer-add-event-listener": "off",
    "unicorn/prefer-dom-node-remove": "off",
  },
});
