export { arm } from "./arm";
export { awaitProcess } from "./await-process";
export { awaitScope } from "./await-scope";
export { bind } from "./bind";
export { cede } from "./cede";
export { fork } from "./fork";
export { halt } from "./halt";
export { invoke } from "./invoke";
export { lookup } from "./lookup";
export { pollProcess } from "./poll-process";
export { pollScope } from "./poll-scope";
export { receive } from "./receive";
export { self } from "./self";
export { spawn } from "./spawn";
export { terminate } from "./terminate";

export type { ArmSyscall } from "./arm";
export type { AwaitProcessSyscall } from "./await-process";
export type { AwaitScopeExit } from "./await-scope";
export type { AwaitScopeSyscall } from "./await-scope";
export type { BindSyscall } from "./bind";
export type { CallDescriptor } from "#src/syscalls-kit/capability";
export type { CapabilityRef } from "#src/syscalls-kit/capability";
export type { CedeSyscall } from "./cede";
export type { ForkSyscall } from "./fork";
export type { HaltSyscall } from "./halt";
export type { InvokeSyscall } from "./invoke";
export type { LookupSyscall } from "./lookup";
export type { PollProcessResult } from "./poll-process";
export type { PollProcessSyscall } from "./poll-process";
export type { PollScopeResult } from "./poll-scope";
export type { PollScopeSyscall } from "./poll-scope";
export type { ScopeStatus } from "./poll-scope";
export type { ProcessExit } from "#src/syscalls-kit/process";
export type { ProcessRef } from "#src/syscalls-kit/process";
export type { ReceiveSyscall } from "./receive";
export type { SelfDescriptor } from "./self";
export type { SelfSyscall } from "./self";
export type { SpawnDescriptor } from "./spawn";
export type { SpawnOptions } from "./spawn";
export type { SpawnRef } from "./spawn";
export type { SpawnSyscall } from "./spawn";
export type { TerminateSyscall } from "./terminate";
