name: Publish docs

on:
  push:
    tags:
      - "@shajara/docs@*"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Node.js and pnpm
        id: setup-pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Build and upload
        uses: withastro/action@v6
        with:
          node-version: ${{ steps.setup-pnpm.outputs.node-version }}
          build-cmd: pnpm --filter @shajara/docs... build
          cache-dir: apps/docs/node_modules/.astro
          out-dir: apps/docs/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v5
